version: '3.7'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.24
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
            - ./data:/etc/mysql/conf.d
            - ./data:/var/log/mysql
        networks:
            - webnet
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PHP_UPLOAD_MAX_FILESIZE: 100MB
        ports:
            - ${ADMIN_PORT}:80
        depends_on:
            - mysql
        networks:
            - webnet

networks:
    webnet:
        name: webnet
        driver: bridge
